### ISSUE TITLE
楼主这个名称dfConf.properties写错了吧，1.3.2启动报错，应该是dbConf.properties

### ISSUE THREAD

**Issue by xiaoxengineer** [fancyerii/wechat-gongzhonghao-crawler#10]
![image](https://user-images.githubusercontent.com/52951339/216499874-ee9fac87-df3f-4bdc-8d7d-dd46f224493c.png)
![image](https://user-images.githubusercontent.com/52951339/216500253-767aca0c-c878-4386-8b84-6246019f12eb.png)

**Comment by fancyerii** [comment]
是的，谢谢
