### ISSUE TITLE
抓取第二个公众号失败

### ISSUE THREAD

**Issue by wtJoker** [fancyerii/wechat-gongzhonghao-crawler#5]
第一个公众号抓取正常，第二个抓取报错误，debug-info里无信息
![image](https://user-images.githubusercontent.com/25917990/134612590-cde0d3bb-b2fa-48d7-b686-8871130002de.png)

**Comment by fancyerii** [comment]
看代码应该是点击后找不到弹出的浏览器窗口，请观察运行的时候是否点击到正确的位置以及是否弹出浏览器？
