### ISSUE TITLE
求助，是否需要保持微信客户端始终保持在前台？

### ISSUE THREAD

**Issue by ghost** [fancyerii/wechat-gongzhonghao-crawler#6]
求助，是否需要保持微信客户端始终保持在前台？ 
我看pywinauto的文档，好像说道click方法并不需要程序界面保持可见状态的，但是实验下来发现必须保持课件才行，不知道大佬有没有遇到这个情况。

**Comment by fancyerii** [comment]
是的，必须要在前台。所以比较好的方法是开一个虚拟机，在虚拟机里安装win10和微信。它的好处是一台机器可以安装多个微信(虚拟机)，而且虚拟机最小化之后还是可以运行的(我用的是ubuntu下的virtualbox，其它虚拟机没试过)。
