### ISSUE TITLE
字体格式不对，显示的都是乱码

### ISSUE THREAD

**Issue by Jeffhop** [fancyerii/wechat-gongzhonghao-crawler#7]
按照教程设置my.ini，创建完成库+表，打开localhost:4567/search,出来的字体全是乱码
![企业微信截图_16424947336699](https://user-images.githubusercontent.com/34859341/149900874-265be224-256e-42d0-936c-476f8f52a952.png)
![企业微信截图_16424947661946](https://user-images.githubusercontent.com/34859341/149900881-11af45c9-33f3-405b-8556-ea841c193be6.png)

**Comment by fancyerii** [comment]
可能需要设置浏览器的编码为utf8，可以根据你的浏览器搜索相关的教程。

**Comment by Jeffhop** [comment]
还是不行，一直显示都是乱码

**Comment by Jeffhop** [comment]
我找到原因了，公众号部分内容为图片，导致爬取的时候就会变成乱码，正文内容是正常的
